# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cot_1_1.ui'
#
# Created: Thu Apr 30 18:36:33 2020
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(598, 448)
        MainWindow.setStyleSheet(_fromUtf8("QLabel {\n"
"color: black;\n"
"background-color: rgba(85, 85, 127, 100);\n"
"}\n"
"\n"
"#atualizar {\n"
"color: white;\n"
"    background-color: rgb(0, 170, 0);\n"
"}"))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.back = QtGui.QFrame(self.centralwidget)
        self.back.setFrameShape(QtGui.QFrame.StyledPanel)
        self.back.setFrameShadow(QtGui.QFrame.Raised)
        self.back.setObjectName(_fromUtf8("back"))
        self.verticalLayoutWidget = QtGui.QWidget(self.back)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 0, 551, 61))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label = QtGui.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI Black"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setTextFormat(QtCore.Qt.LogText)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout.addWidget(self.label)
        self.frame = QtGui.QFrame(self.back)
        self.frame.setGeometry(QtCore.QRect(10, 70, 551, 331))
        self.frame.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.formLayoutWidget = QtGui.QWidget(self.frame)
        self.formLayoutWidget.setGeometry(QtCore.QRect(90, 9, 181, 41))
        self.formLayoutWidget.setObjectName(_fromUtf8("formLayoutWidget"))
        self.formLayout = QtGui.QFormLayout(self.formLayoutWidget)
        self.formLayout.setMargin(0)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.jogoLabel = QtGui.QLabel(self.formLayoutWidget)
        self.jogoLabel.setObjectName(_fromUtf8("jogoLabel"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.jogoLabel)
        self.dataLabel = QtGui.QLabel(self.formLayoutWidget)
        self.dataLabel.setObjectName(_fromUtf8("dataLabel"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.dataLabel)
        self.label_2 = QtGui.QLabel(self.formLayoutWidget)
        self.label_2.setText(_fromUtf8(""))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.label_2)
        self.label_3 = QtGui.QLabel(self.formLayoutWidget)
        self.label_3.setText(_fromUtf8(""))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.label_3)
        self.formLayoutWidget_2 = QtGui.QWidget(self.frame)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(280, 10, 181, 41))
        self.formLayoutWidget_2.setObjectName(_fromUtf8("formLayoutWidget_2"))
        self.formLayout_2 = QtGui.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setMargin(0)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.homeLabel = QtGui.QLabel(self.formLayoutWidget_2)
        self.homeLabel.setObjectName(_fromUtf8("homeLabel"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.homeLabel)
        self.awayLabel = QtGui.QLabel(self.formLayoutWidget_2)
        self.awayLabel.setObjectName(_fromUtf8("awayLabel"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.awayLabel)
        self.label_4 = QtGui.QLabel(self.formLayoutWidget_2)
        self.label_4.setText(_fromUtf8(""))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.label_4)
        self.label_5 = QtGui.QLabel(self.formLayoutWidget_2)
        self.label_5.setText(_fromUtf8(""))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.label_5)
        self.tableWidget = QtGui.QTableWidget(self.frame)
        self.tableWidget.setGeometry(QtCore.QRect(90, 60, 371, 221))
        self.tableWidget.setMinimumSize(QtCore.QSize(0, 221))
        self.tableWidget.setFrameShape(QtGui.QFrame.Box)
        self.tableWidget.setFrameShadow(QtGui.QFrame.Sunken)
        self.tableWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(6)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(107)
        self.horizontalLayoutWidget = QtGui.QWidget(self.frame)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(90, 290, 371, 31))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButton_2 = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.atualizar = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.atualizar.setObjectName(_fromUtf8("atualizar"))
        self.horizontalLayout.addWidget(self.atualizar)
        self.gridLayout.addWidget(self.back, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 598, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuMenu = QtGui.QMenu(self.menubar)
        self.menuMenu.setObjectName(_fromUtf8("menuMenu"))
        self.menuDatabase = QtGui.QMenu(self.menubar)
        self.menuDatabase.setObjectName(_fromUtf8("menuDatabase"))
        self.menuExportar = QtGui.QMenu(self.menubar)
        self.menuExportar.setObjectName(_fromUtf8("menuExportar"))
        MainWindow.setMenuBar(self.menubar)
        self.actionOdds = QtGui.QAction(MainWindow)
        self.actionOdds.setObjectName(_fromUtf8("actionOdds"))
        self.menuMenu.addAction(self.actionOdds)
        self.menubar.addAction(self.menuMenu.menuAction())
        self.menubar.addAction(self.menuDatabase.menuAction())
        self.menubar.addAction(self.menuExportar.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Cotações", None))
        self.label.setText(_translate("MainWindow", "COTAÇÃO 1_1", None))
        self.jogoLabel.setText(_translate("MainWindow", "Jogo", None))
        self.dataLabel.setText(_translate("MainWindow", "Data", None))
        self.homeLabel.setText(_translate("MainWindow", "Home", None))
        self.awayLabel.setText(_translate("MainWindow", "Away", None))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "Bet365", None))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "188bet", None))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "Vbet", None))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "Betway", None))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "Pinnacle", None))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "1xbet", None))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Home", None))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Draw", None))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Away", None))
        self.pushButton_2.setText(_translate("MainWindow", "Consulta", None))
        self.atualizar.setText(_translate("MainWindow", "Atualizar", None))
        self.menuMenu.setTitle(_translate("MainWindow", "Menu", None))
        self.menuDatabase.setTitle(_translate("MainWindow", "Database", None))
        self.menuExportar.setTitle(_translate("MainWindow", "Exportar", None))
        self.actionOdds.setText(_translate("MainWindow", "Odds", None))

