# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cot_1_1.ui'
#
# Created: Fri May 08 02:10:32 2020
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(428, 499)
        MainWindow.setStyleSheet(_fromUtf8("QLabel{\n"
"font-size: 14px;\n"
"}"))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.back = QtGui.QFrame(self.centralwidget)
        self.back.setFrameShape(QtGui.QFrame.StyledPanel)
        self.back.setFrameShadow(QtGui.QFrame.Raised)
        self.back.setObjectName(_fromUtf8("back"))
        self.gridLayoutWidget = QtGui.QWidget(self.back)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 220, 371, 223))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_2.setContentsMargins(2, -1, -1, -1)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.tableWidget = QtGui.QTableWidget(self.gridLayoutWidget)
        self.tableWidget.setMinimumSize(QtCore.QSize(0, 221))
        self.tableWidget.setFrameShape(QtGui.QFrame.Box)
        self.tableWidget.setFrameShadow(QtGui.QFrame.Sunken)
        self.tableWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget.setAutoScroll(True)
        self.tableWidget.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.tableWidget.setShowGrid(True)
        self.tableWidget.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(6)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        item.setFlags(QtCore.Qt.ItemIsDragEnabled)
        self.tableWidget.setItem(4, 2, item)
        self.tableWidget.horizontalHeader().setVisible(True)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(107)
        self.tableWidget.verticalHeader().setVisible(True)
        self.tableWidget.verticalHeader().setCascadingSectionResizes(False)
        self.tableWidget.verticalHeader().setDefaultSectionSize(30)
        self.tableWidget.verticalHeader().setMinimumSectionSize(20)
        self.tableWidget.verticalHeader().setSortIndicatorShown(False)
        self.tableWidget.verticalHeader().setStretchLastSection(True)
        self.gridLayout_2.addWidget(self.tableWidget, 0, 0, 1, 1)
        self.groupBox = QtGui.QGroupBox(self.back)
        self.groupBox.setGeometry(QtCore.QRect(20, 30, 371, 181))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.formLayoutWidget = QtGui.QWidget(self.groupBox)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 20, 255, 151))
        self.formLayoutWidget.setObjectName(_fromUtf8("formLayoutWidget"))
        self.formLayout = QtGui.QFormLayout(self.formLayoutWidget)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setMargin(0)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.comboBox = QtGui.QComboBox(self.formLayoutWidget)
        self.comboBox.setMaximumSize(QtCore.QSize(247, 16777215))
        self.comboBox.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.comboBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.comboBox.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToMinimumContentsLength)
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.formLayout.setWidget(1, QtGui.QFormLayout.SpanningRole, self.comboBox)
        self.comboBox_2 = QtGui.QComboBox(self.formLayoutWidget)
        self.comboBox_2.setMinimumSize(QtCore.QSize(247, 15))
        self.comboBox_2.setMaximumSize(QtCore.QSize(115, 20))
        self.comboBox_2.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.comboBox_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.comboBox_2.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToMinimumContentsLengthWithIcon)
        self.comboBox_2.setObjectName(_fromUtf8("comboBox_2"))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.comboBox_2)
        self.comboBox_3 = QtGui.QComboBox(self.formLayoutWidget)
        self.comboBox_3.setMinimumSize(QtCore.QSize(247, 0))
        self.comboBox_3.setObjectName(_fromUtf8("comboBox_3"))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.comboBox_3)
        self.escolhaOEsporteLabel = QtGui.QLabel(self.formLayoutWidget)
        self.escolhaOEsporteLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.escolhaOEsporteLabel.setObjectName(_fromUtf8("escolhaOEsporteLabel"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.SpanningRole, self.escolhaOEsporteLabel)
        self.escolhaALigaLabel = QtGui.QLabel(self.formLayoutWidget)
        self.escolhaALigaLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.escolhaALigaLabel.setObjectName(_fromUtf8("escolhaALigaLabel"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.SpanningRole, self.escolhaALigaLabel)
        self.escolhaOJogoLabel = QtGui.QLabel(self.formLayoutWidget)
        self.escolhaOJogoLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.escolhaOJogoLabel.setObjectName(_fromUtf8("escolhaOJogoLabel"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.SpanningRole, self.escolhaOJogoLabel)
        self.pushButton = QtGui.QPushButton(self.groupBox)
        self.pushButton.setGeometry(QtCore.QRect(280, 140, 75, 23))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.gridLayout.addWidget(self.back, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 428, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuMenu = QtGui.QMenu(self.menubar)
        self.menuMenu.setObjectName(_fromUtf8("menuMenu"))
        self.menuDatabase = QtGui.QMenu(self.menubar)
        self.menuDatabase.setObjectName(_fromUtf8("menuDatabase"))
        self.menuExportar = QtGui.QMenu(self.menubar)
        self.menuExportar.setObjectName(_fromUtf8("menuExportar"))
        MainWindow.setMenuBar(self.menubar)
        self.actionOdds = QtGui.QAction(MainWindow)
        self.actionOdds.setObjectName(_fromUtf8("actionOdds"))
        self.menuMenu.addAction(self.actionOdds)
        self.menubar.addAction(self.menuMenu.menuAction())
        self.menubar.addAction(self.menuDatabase.menuAction())
        self.menubar.addAction(self.menuExportar.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Cotações", None))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "Bet365", None))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "188bet", None))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "Vbet", None))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "Betway", None))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "Pinnacle", None))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "1xbet", None))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Home", None))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Draw", None))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Away", None))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.groupBox.setTitle(_translate("MainWindow", "Filtros", None))
        self.comboBox.setItemText(0, _translate("MainWindow", "Esportes", None))
        self.comboBox.setItemText(1, _translate("MainWindow", "soccer", None))
        self.comboBox.setItemText(2, _translate("MainWindow", "table_tenis", None))
        self.comboBox.setItemText(3, _translate("MainWindow", "tennis", None))
        self.comboBox.setItemText(4, _translate("MainWindow", "volleyball", None))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "Escolha a liga", None))
        self.comboBox_3.setItemText(0, _translate("MainWindow", "Escolha o jogo", None))
        self.escolhaOEsporteLabel.setText(_translate("MainWindow", "Escolha o Esporte:", None))
        self.escolhaALigaLabel.setText(_translate("MainWindow", "Escolha a Liga:", None))
        self.escolhaOJogoLabel.setText(_translate("MainWindow", "Escolha o Jogo:", None))
        self.pushButton.setText(_translate("MainWindow", "Buscar", None))
        self.menuMenu.setTitle(_translate("MainWindow", "Menu", None))
        self.menuDatabase.setTitle(_translate("MainWindow", "Database", None))
        self.menuExportar.setTitle(_translate("MainWindow", "Exportar", None))
        self.actionOdds.setText(_translate("MainWindow", "Odds", None))
